apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: social-platform-prod
  namespace: argocd
  labels:
    environment: production
spec:
  project: default
  source:
    repoURL: https://bitbucket.org/yourorg/social-platform-k8s-manifests
    targetRevision: main
    path: environments/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: social-platform-prod
  syncPolicy:
    # Manual sync for production
    syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m