apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: social-platform-staging
  namespace: argocd
  labels:
    environment: staging
spec:
  project: default
  source:
    repoURL: https://bitbucket.org/yourorg/social-platform-k8s-manifests
    targetRevision: staging
    path: environments/staging
  destination:
    server: https://kubernetes.default.svc
    namespace: social-platform-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
